steps:
    - id: "Store env vars string"
      name: "gcr.io/cloud-builders/gcloud"
      entrypoint: bash
      args:
        - -c
        - |
          _ENV_VARS="CLIENT_ID=${_CLIENT_ID},CLIENT_SECRET=${_CLIENT_SECRET},USER_AGENT=${_USER_AGENT},REDDIT_USERNAME=${_REDDIT_USERNAME},REDDIT_PASSWORD=${_REDDIT_PASSWORD},KERAS_PREDICTION_URL=${_KERAS_PREDICTION_URL}"

          echo ${_ENV_VARS} > /workspace/env_vars

    - id: "Deploy scrapePosts function"
      name: "gcr.io/cloud-builders/gcloud"
      entrypoint: bash
      args:
        - -c
        - |
          _ENV_VARS=$(cat /workspace/env_vars)
          ./scripts/deployFunction.sh scrapePosts "${_ENV_VARS}"
      dir: "functions"
      waitFor: ["Store env vars string"]

    - id: "Deploy ingestImages function"
      name: "gcr.io/cloud-builders/gcloud"
      entrypoint: bash
      args:
        - -c
        - |
          _ENV_VARS=$(cat /workspace/env_vars)
          ./scripts/deployFunction.sh ingestImages "${_ENV_VARS}"
      dir: "functions"
      waitFor: ["Store env vars string"]

    - id: "Deploy ingestPosts function"
      name: "gcr.io/cloud-builders/gcloud"
      entrypoint: bash
      args:
        - -c
        - |
          _ENV_VARS=$(cat /workspace/env_vars)
          ./scripts/deployFunction.sh ingestPosts "${_ENV_VARS}"
      dir: "functions"
      waitFor: ["Store env vars string"]

    - id: "Deploy predict function"
      name: "gcr.io/cloud-builders/gcloud"
      entrypoint: bash
      args:
        - -c
        - |
          _ENV_VARS=$(cat /workspace/env_vars)
          ./scripts/deployFunction.sh predict "${_ENV_VARS}"
      dir: "functions"
      waitFor: ["Store env vars string"]

    - id: "Deploy downloadPostImages function"
      name: "gcr.io/cloud-builders/gcloud"
      entrypoint: bash
      args:
        - -c
        - |
          _ENV_VARS=$(cat /workspace/env_vars)
          ./scripts/deployFunction.sh downloadPostImages "${_ENV_VARS}"
      dir: "functions"
      waitFor: ["Store env vars string"]

    - id: "Deploy filterExplicitImages function"
      name: "gcr.io/cloud-builders/gcloud"
      entrypoint: bash
      args:
        - -c
        - |
          _ENV_VARS=$(cat /workspace/env_vars)
          ./scripts/deployFunction.sh filterExplicitImages "${_ENV_VARS}"
      dir: "functions"
      waitFor: ["Store env vars string"]

    - id: "Deploy ingestPartialPosts function"
      name: "gcr.io/cloud-builders/gcloud"
      entrypoint: bash
      args:
        - -c
        - |
          _ENV_VARS=$(cat /workspace/env_vars)
          ./scripts/deployFunction.sh ingestPartialPosts "${_ENV_VARS}"
      dir: "functions"
      waitFor: ["Store env vars string"]

    - id: "Deploy processImages function"
      name: "gcr.io/cloud-builders/gcloud"
      entrypoint: bash
      args:
        - -c
        - |
          _ENV_VARS=$(cat /workspace/env_vars)
          ./scripts/deployFunction.sh processImages "${_ENV_VARS}"
      dir: "functions"
      waitFor: ["Store env vars string"]

    - id: "Deploy updatePostHashes function"
      name: "gcr.io/cloud-builders/gcloud"
      entrypoint: bash
      args:
        - -c
        - |
          _ENV_VARS=$(cat /workspace/env_vars)
          ./scripts/deployFunction.sh updatePostHashes "${_ENV_VARS}"
      dir: "functions"
      waitFor: ["Store env vars string"]

substitutions:
  _CLIENT_ID: ""
  _CLIENT_SECRET: ""
  _USER_AGENT: ""
  _REDDIT_USERNAME: ""
  _REDDIT_PASSWORD: ""
  _KERAS_PREDICTION_URL: ""