steps:
    - id: "Store env vars string"
      name: "gcr.io/cloud-builders/gcloud"
      entrypoint: bash
      args:
        - -c
        - |
          echo "CLIENT_ID=${_CLIENT_ID},CLIENT_SECRET=${_CLIENT_SECRET},USER_AGENT=${_USER_AGENT},REDDIT_USERNAME=${_REDDIT_USERNAME},REDDIT_PASSWORD=${_REDDIT_PASSWORD},KERAS_PREDICTION_URL=${_KERAS_PREDICTION_URL}" > /workspace/env_vars

    - id: "Deploy scrapePosts function"
      name: "gcr.io/cloud-builders/gcloud"
      entrypoint: bash
      args:
        - -c
        - |
          bash ./scripts/deployFunction.sh scrapePosts "$(cat /workspace/env_vars)"
      dir: "functions"
      waitFor: ["Store env vars string"]

    - id: "Deploy predict function"
      name: "gcr.io/cloud-builders/gcloud"
      entrypoint: bash
      args:
        - -c
        - |
          bash ./scripts/deployFunction.sh predict "$(cat /workspace/env_vars)"
      dir: "functions"
      waitFor: ["Store env vars string"]

    - id: "Deploy downloadPostImages function"
      name: "gcr.io/cloud-builders/gcloud"
      entrypoint: bash
      args:
        - -c
        - |
          bash ./scripts/deployFunction.sh downloadPostImages "$(cat /workspace/env_vars)"
      dir: "functions"
      waitFor: ["Store env vars string"]

    - id: "Deploy filterExplicitImages function"
      name: "gcr.io/cloud-builders/gcloud"
      entrypoint: bash
      args:
        - -c
        - |
          bash ./scripts/deployFunction.sh filterExplicitImages "$(cat /workspace/env_vars)"
      dir: "functions"
      waitFor: ["Store env vars string"]

    - id: "Deploy ingestPartialPosts function"
      name: "gcr.io/cloud-builders/gcloud"
      entrypoint: bash
      args:
        - -c
        - |
          bash ./scripts/deployFunction.sh ingestPartialPosts "$(cat /workspace/env_vars)"
      dir: "functions"
      waitFor: ["Store env vars string"]

    - id: "Deploy processImages function"
      name: "gcr.io/cloud-builders/gcloud"
      entrypoint: bash
      args:
        - -c
        - |
          bash ./scripts/deployFunction.sh processImages "$(cat /workspace/env_vars)"
      dir: "functions"
      waitFor: ["Store env vars string"]

    - id: "Deploy updatePostHashes function"
      name: "gcr.io/cloud-builders/gcloud"
      entrypoint: bash
      args:
        - -c
        - |
          bash ./scripts/deployFunction.sh updatePostHashes "$(cat /workspace/env_vars)"
      dir: "functions"
      waitFor: ["Store env vars string"]

    - id: "Deploy deleteStagingImages function"
      name: "gcr.io/cloud-builders/gcloud"
      entrypoint: bash
      args:
        - -c
        - |
          bash ./scripts/deployFunction.sh deleteStagingImages "$(cat /workspace/env_vars)"
      dir: "functions"
      waitFor: ["Store env vars string"]

substitutions:
  _CLIENT_ID: ""
  _CLIENT_SECRET: ""
  _USER_AGENT: ""
  _REDDIT_USERNAME: ""
  _REDDIT_PASSWORD: ""
  _KERAS_PREDICTION_URL: ""
