steps:
    - id: "Deploy scrapePosts workflow"
      name: "gcr.io/cloud-builders/gcloud"
      entrypoint: bash
      args:
        - -c
        - |
          bash ./scripts/deployWorkflow.sh scrapePostsWorkflow
      dir: "workflows"
      waitFor: ["-"]

    - id: "Deploy ingestImage workflow"
      name: "gcr.io/cloud-builders/gcloud"
      entrypoint: bash
      args:
        - -c
        - |
          bash ./scripts/deployWorkflow.sh ingestImageWorkflow
      dir: "workflows"
      waitFor: ["-"]
