version: '2'

services:
    redesign:
        build:
            context: ./redesign
            args:
                app_env: development
        image: redesign
        ports:
            - "3001:3000"
        volumes:
            - ./redesign:/redesign
            - redesign-deps:/redesign/node_modules
    backend:
        build: ./backend
        image: backend
        ports:
            - "5000:5000"
        command: python src/main.py
        volumes:
            - ./backend/:/app
            - ./models/:/var/model-storage
            - ./:/gcp
        environment:
            - GOOGLE_APPLICATION_CREDENTIALS=/gcp/easy-dank-meme-classifier-account.json
            - FLASK_ENV=development

volumes:
    redesign-deps:
